apiVersion: v1
kind: Namespace
metadata:
  name: kargo-demo
  labels:
    kargo.akuity.io/project: "true"
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo-demo
spec:
  subscriptions:
    repos:
      images:
      - repoURL: ghcr.io/tautcius/kargo-demo-app
        semverConstraint: ^0.0.1
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/Tautcius/kargo-demo
      writeBranch: stage/test
      kustomize:
        images:
        - image: ghcr.io/tautcius/kargo-demo-app
          path: stages/test
    argoCDAppUpdates:
    - appName: kargo-demo-test
      appNamespace: argocd
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: uat
  namespace: kargo-demo
spec:
  subscriptions:
    upstreamStages:
    - name: test
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/Tautcius/kargo-demo
      writeBranch: stage/uat
      kustomize:
        images:
        - image: ghcr.io/tautcius/kargo-demo-app
          path: stages/uat
    argoCDAppUpdates:
    - appName: kargo-demo-uat
      appNamespace: argocd
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-demo
spec:
  subscriptions:
    upstreamStages:
    - name: uat
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/Tautcius/kargo-demo
      writeBranch: stage/prod
      kustomize:
        images:
        - image: nginx
          path: stages/prod
    argoCDAppUpdates:
    - appName: kargo-demo-prod
      appNamespace: argocd
