kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kargo-quickstart
nodes:
- extraPortMappings:
  - containerPort: 31443 # Argo CD dashboard
    hostPort: 8443
  - containerPort: 31444 # Kargo dashboard
    hostPort: 8444
  - containerPort: 30081 # test application instance
    hostPort: 8081
  - containerPort: 30082 # UAT application instance
    hostPort: 8082
  - containerPort: 30083 # prod application instance
    hostPort: 8083