---
apiVersion: v1
kind: Namespace
metadata:
  name: test-sync
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-sync
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Tautcius/kargo-demo
    targetRevision: main
    path: sync
  destination:
    server: https://kubernetes.default.svc
    namespace: test-sync