apiVersion: batch/v1
kind: Job
metadata:
  name: e2e-test
spec:
  ttlSecondsAfterFinished: 15
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["ls","/knoldus"]
      restartPolicy: Never
  backoffLimit: 4

