apiVersion: apps/v1
kind: Deployment
metadata:
  name: kargo-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kargo-demo
  template:
    metadata:
      labels:
        app: kargo-demo
    spec:
      containers:
      - name: kargo-demo-app 
        image: ghcr.io/tautcius/kargo-demo-app:0.0.1
        env:
        - name: ENV
          value: "nothing"

