apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- configmap.yaml

patches:
- target:
    kind: Service
    name: kargo-demo
  patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30083
- target:
    kind: Deployment
    name: kargo-demo
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: "prod"
